method: bayes
    
metric : 
    name: loss
    goal: minimize   

parameters :
    LR: 
        distribution: log_uniform_values
        min: 0.00001
        max: 0.1
    CC:
        distribution: log_uniform_values
        min: 0.00001
        max: 0.1
    JACOBIAN:
        distribution: log_uniform_values
        min: 0.01
        max: 1

